[build]
  functions = "netlify/functions"
  publish="public"
  command="npm install"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200